---
abstract: 'Moops Object-Oriented Programming Sugar'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.006, CPAN::Meta::Converter version 2.120921'
keywords: []
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moops
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
provides:
  Class::Tiny::Antlers:
    file: lib/Class/Tiny/Antlers.pm
    version: 0.011
  Moops:
    file: lib/Moops.pm
    version: 0.011
  Moops::DefineKeyword:
    file: lib/Moops/DefineKeyword.pm
    version: 0.011
  Moops::ImportSet:
    file: lib/Moops/ImportSet.pm
    version: 0.011
  Moops::Keyword:
    file: lib/Moops/Keyword.pm
    version: 0.011
  Moops::Keyword::Class:
    file: lib/Moops/Keyword/Class.pm
    version: 0.011
  Moops::Keyword::Role:
    file: lib/Moops/Keyword/Role.pm
    version: 0.011
  Moops::MethodModifiers:
    file: lib/Moops/MethodModifiers.pm
    version: 0.011
  Moops::Parser:
    file: lib/Moops/Parser.pm
    version: 0.011
  Moops::TraitFor::Keyword::dirty:
    file: lib/Moops/TraitFor/Keyword/dirty.pm
    version: 0.011
  Moops::TraitFor::Keyword::mutable:
    file: lib/Moops/TraitFor/Keyword/mutable.pm
    version: 0.011
  Moops::TraitFor::Keyword::ro:
    file: lib/Moops/TraitFor/Keyword/ro.pm
    version: 0.011
  Moops::TraitFor::Keyword::rw:
    file: lib/Moops/TraitFor/Keyword/rw.pm
    version: 0.011
  Moops::TraitFor::Keyword::rwp:
    file: lib/Moops/TraitFor/Keyword/rwp.pm
    version: 0.011
requires:
  Devel::Pragma: 0.54
  Exporter::TypeTiny: 0.022
  Function::Parameters: 1.0201
  Import::Into: 1.000000
  Keyword::Simple: 0.01
  Module::Runtime: 0.013
  Moo: 1.003000
  MooX::late: 0.014
  MooseX::MungeHas: 0.002
  Scalar::Util: 1.24
  Try::Tiny: 0.12
  Type::Utils: 0.022
  namespace::sweep: 0.006
  perl: 5.014
  true: 0.18
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Moops/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Moops
  homepage: https://metacpan.org/release/Moops
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moops
version: 0.011
x_provides_scripts: {}
