---
abstract: 'Moops Object-Oriented Programming Sugar'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  CPAN::Meta::Requirements: 2.000
  ExtUtils::MakeMaker: 6.17
conflicts:
  MooseX::Types::Common: '== 0.001011'
  MooseX::Types::URI: '== 0.04'
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moops
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features:
  Moo:
    description: 'allow classes and roles to be built with Moo'
  Moose:
    description: 'allow classes and roles to be built with Moose'
    recommends:
      MooseX::XSAccessor: 0
    requires:
      Moose: 2.0600
  Mouse:
    description: 'allow classes and roles to be built with Mouse'
    requires:
      Mouse: 1.00
  Tiny:
    description: 'allow classes and roles to be built with Class::Tiny/Role::Tiny'
    requires:
      Class::Tiny::Antlers: 0
      Role::Tiny: 1.000000
provides:
  Moops:
    file: lib/Moops.pm
    version: 0.029
  Moops::ImportSet:
    file: lib/Moops/ImportSet.pm
    version: 0.029
  Moops::Keyword:
    file: lib/Moops/Keyword.pm
    version: 0.029
  Moops::Keyword::Class:
    file: lib/Moops/Keyword/Class.pm
    version: 0.029
  Moops::Keyword::Library:
    file: lib/Moops/Keyword/Library.pm
    version: 0.029
  Moops::Keyword::Role:
    file: lib/Moops/Keyword/Role.pm
    version: 0.029
  Moops::MethodModifiers:
    file: lib/Moops/MethodModifiers.pm
    version: 0.029
  Moops::Parser:
    file: lib/Moops/Parser.pm
    version: 0.029
  Moops::TraitFor::Keyword::assertions:
    file: lib/Moops/TraitFor/Keyword/assertions.pm
    version: 0.029
  Moops::TraitFor::Keyword::dirty:
    file: lib/Moops/TraitFor/Keyword/dirty.pm
    version: 0.029
  Moops::TraitFor::Keyword::fp:
    file: lib/Moops/TraitFor/Keyword/fp.pm
    version: 0.029
  Moops::TraitFor::Keyword::mutable:
    file: lib/Moops/TraitFor/Keyword/mutable.pm
    version: 0.029
  Moops::TraitFor::Keyword::ro:
    file: lib/Moops/TraitFor/Keyword/ro.pm
    version: 0.029
  Moops::TraitFor::Keyword::rw:
    file: lib/Moops/TraitFor/Keyword/rw.pm
    version: 0.029
  Moops::TraitFor::Keyword::rwp:
    file: lib/Moops/TraitFor/Keyword/rwp.pm
    version: 0.029
  MooseX::FunctionParametersInfo:
    file: lib/MooseX/FunctionParametersInfo.pm
    version: 0.029
  MooseX::FunctionParametersInfo::Trait::Method:
    file: lib/MooseX/FunctionParametersInfo.pm
    version: 0.029
  MooseX::FunctionParametersInfo::Trait::WrappedMethod:
    file: lib/MooseX/FunctionParametersInfo.pm
    version: 0.029
  PerlX::Assert:
    file: lib/PerlX/Assert.pm
    version: 0.029
  PerlX::Define:
    file: lib/PerlX/Define.pm
    version: 0.029
recommends:
  Keyword::Simple: 0.02
requires:
  Devel::Pragma: 0.54
  Exporter::Tiny: 0.026
  Import::Into: 1.000000
  Kavorka: 0.023
  Keyword::Simple: 0.01
  Lexical::Accessor: 0.003
  Module::Runtime: 0.013
  Moo: 1.003000
  MooX::late: 0.014
  MooseX::MungeHas: 0.002
  Scalar::Util: 1.24
  Sub::Name: 0
  Try::Tiny: 0.12
  Type::Utils: 0.024
  namespace::sweep: 0.006
  perl: 5.014
  true: 0.18
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Moops/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Moops
  homepage: https://metacpan.org/release/Moops
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moops
version: 0.029
